baseURL = 'https://enricocolon.github.io/'
languageCode = 'en-us'
title = "Enrico Colón's Homepage"
theme = 'hugo-xmin'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[[menu.main]]
  name = 'About'
  url = 'https://enricocolon.github.io/#about'
  weight = 1
[[menu.main]]
  name = 'Research'
  url = 'https://enricocolon.github.io/#research'
  weight = 2
[[menu.main]]
  name = 'Expository'
  url = 'https://enricocolon.github.io/#expository'
  weight = 3
[[menu.main]]
  name = 'Teaching'
  url = 'https://enricocolon.github.io/#teaching'
  weight = 4
[[menu.main]]
  name = 'Leadership and Outreach'
  url = 'https://enricocolon.github.io/#leadership-and-outreach'
  weight = 5
[[menu.main]]
  name = 'Code'
  url = 'https://github.com/enricocolon'
  weight = 6
